### ISSUE TITLE
Bug: Mishandling of missing values

### ISSUE THREAD

**Issue by akarlinsky** [tesselle/tabula#27]
Hi, thanks for a great package!

I encountered a bug with the way it handles missing values:

code to replicate error:
```
a <- c(1,1,NA,1)   
index_simpson(a)   
index_simpson(a, na.rm = T)   
```

Output (on both calls to `index_simpson`:
```
Error in if (!all(is_whole(x, ...))) { : 
  missing value where TRUE/FALSE needed
```

**Comment by nfrerebeau** [comment]
Thanks for pointing out this bug, it should work fine now.
